apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistent_volume_claim.name }}
  namespace: default
  labels:
    app: {{ .Values.persistent_volume_claim.name }}
spec:
  storageClassName: {{ .Values.persistent_volume.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistent_volume_claim.storage }}