apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb_service.name }}
  namespace: {{ .Values.mongodb_deployment.namespace }}
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: {{ .Values.mongodb_service.ports.port }}
      targetPort: {{ .Values.mongodb_service.ports.targetPort }}