apiVersion: apps/v1
kind: Deployment
metadata:
  name:  app-deployment
  namespace: staging
  labels:
    app:  app-deployment
spec:
  selector:
    matchLabels:
      app: app-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app:  app-deployment
    spec:
      containers:
      - name:  app-deployment
        image:   nvb20/custom-actions:prod
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        ports:
        - containerPort:  5000
          name:  app-deployment
        volumeMounts:
        - name: my-chat-app
          mountPath: /etc/my-chat-app
      volumes:
        - name: my-chat-app
          hostPath:
            path: /usr/app/code
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: staging
spec:
  selector:
    app: app-service
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: app-service
    protocol: TCP
    port: 5000
    targetPort: 5000
   