apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_deployment.name }}
  namespace: {{ .Values.app_deployment.namespace }}
  labels:
    app: chatroom
spec:
  replicas: {{ .Values.app_deployment.replicas }}
  selector:
    matchLabels:
      app: chatroom
  template:
    metadata:
      labels:
        app: chatroom
    spec:
      containers:
      - name: {{ .Values.app_deployment.containers.name }}
        image: {{ .Values.app_deployment.containers.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.app_deployment.containers.containerPort }}
      restartPolicy: Always