---
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "chat-ingress"
  namespace: {{ .Values.app_deployment.namespace }}
spec:
  defaultBackend:
    service:
      name: {{ .Values.app_service.name }}
      port:
        number: {{ .Values.app_service.port }}
status:
  loadBalancer: {}
