kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: service-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fabric8-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

# kind: ClusterRole
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: pods-list
# rules:
# - apiGroups: [""]
#   resources: ["pods", "services"]
#   verbs: ["get", "watch", "list"]

# ---
# kind: ClusterRoleBinding
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: pods-list-binding
# subjects:
# - kind: ServiceAccount
#   name: default
#   namespace: staging
# roleRef:
#   kind: ClusterRole
#   name: pods-list
#   apiGroup: rbac.authorization.k8s.io

# kubectl auth can-i list services --as=system:serviceaccount:default:app-service --namespace=default

